version = 0.1

[default.deploy.parameters]
stack_name = "sys-user-management"
resolve_s3 = true
s3_prefix = "sys-user-management"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
